/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Dokument;
import domen.StavkaDokumenta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabeleStavke;

/**
 *
 * @author stefa
 */
public class FrmIzmeniDokument extends javax.swing.JFrame {

    Dokument d;
    double ukupnaCena;
    ArrayList<StavkaDokumenta> listaStavki;
    ArrayList<StavkaDokumenta> listaIzmenjenihStavki = new ArrayList<>();
    StavkaDokumenta sd;
    ModelTabeleStavke mts;

    /**
     * Creates new form FrmIzmeniDokument
     */
    public FrmIzmeniDokument(Dokument d) {
        initComponents();
        setLocationRelativeTo(null);
        this.d = d;

        lblID.setText(String.valueOf(d.getDokumentID()));
        lblKlijent.setText(d.getKlijent().getNazivKlijenta());
        lblZaposleni.setText(d.getZaposleni().getIme() + " " + d.getZaposleni().getPrezime());

        if (d.getStatusDokumenta().equals("Izdat")) {
            btnObrisi.setEnabled(false);
            btnUsluga.setEnabled(false);
            btnSacuvaj.setEnabled(false);
            cbStatus.setEnabled(false);
            cbTip.setEnabled(false);
            txtDatum.setEnabled(false);
            cbStatus.setSelectedItem("Izdat");
        }else{
            cbStatus.setSelectedItem("U obradi");
        }
        cbTip.setSelectedItem(d.getTipDokumenta());

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        sdf.setLenient(false);
        txtDatum.setText(sdf.format(d.getDatum()));

        txtUkupno.setText(String.valueOf(d.getUkupnaCena()));
        ukupnaCena = d.getUkupnaCena();

        listaStavki = (ArrayList<StavkaDokumenta>) Kontroler.getInstance().vratiListuStavki(d);

        popuniTabeluStavki();
    }

    public void setSd(StavkaDokumenta sd) {
        this.sd = sd;
    }

    public void dodajStavku(StavkaDokumenta sd) {
        listaStavki.add(sd);
        listaIzmenjenihStavki.add(sd);
    }

    public Dokument getDokument() {
        return d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnUsluga = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTip = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        lblNaslov = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblKlijent = new javax.swing.JLabel();
        lblZaposleni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        jLabel9.setText("Stavke dokumenta:");

        btnUsluga.setText("Dodaj stavku");
        btnUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUslugaActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj dokument");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel4.setText("Ukupna cena:");

        txtUkupno.setText("0");

        jLabel10.setText("RSD");

        cbTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Racun", "Predracun", "Ponuda" }));

        jLabel6.setText("Tip dokumenta:");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U obradi", "Izdat" }));

        jLabel7.setText("Status dokumenta:");

        jLabel11.setText("Datum:");

        txtDatum.setText("01.01.2024");

        lblNaslov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNaslov.setText("Izmena dokumenta");

        jLabel8.setText("Klijent:");

        jLabel12.setText("Zaposleni:");

        jLabel13.setText("ID:");

        lblID.setText("jLabel1");

        lblKlijent.setText("jLabel1");

        lblZaposleni.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(286, 286, 286))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(259, 259, 259)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lblNaslov))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblKlijent))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblZaposleni))
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsluga)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUkupno)
                    .addComponent(jLabel10)
                    .addComponent(btnSacuvaj))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUslugaActionPerformed
        FrmKreirajStavku fks = new FrmKreirajStavku(this, true);
        fks.setVisible(true);
        ukupnaCena += sd.getCenaStavke();
        txtUkupno.setText(String.valueOf(ukupnaCena));
    }//GEN-LAST:event_btnUslugaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        mts = (ModelTabeleStavke) tblStavke.getModel();
        int red = tblStavke.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku dokumenta", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            StavkaDokumenta s = mts.vratiStavku(red);
            s.setPostoji(false);
            listaIzmenjenihStavki.add(s);
            this.ukupnaCena -= s.getCenaStavke();
            txtUkupno.setText(String.valueOf(ukupnaCena));
            mts.obrisiStavku(s);
            popuniTabeluStavki();
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (txtUkupno.getText().isEmpty() || txtUkupno.getText().equals("0") || listaStavki.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate izabrati bar jednu uslugu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDatum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate ispravno uneti datum", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        d.setUkupnaCena(ukupnaCena);
        d.setListaStavki(listaIzmenjenihStavki);
        d.setTipDokumenta(String.valueOf(cbTip.getSelectedItem()));
        d.setStatusDokumenta(String.valueOf(cbStatus.getSelectedItem()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        sdf.setLenient(false);
        try {
            Date datum = sdf.parse(txtDatum.getText());
            d.setDatum(datum);
        } catch (ParseException ex) {
            //Logger.getLogger(FrmKreirajDokument.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Uneli ste datum u pogresnom formatu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Kontroler.getInstance().zapamtiDokument(d)) {
            this.dispose();
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    public void popuniTabeluStavki() {
        mts = new ModelTabeleStavke(listaStavki);
        tblStavke.setModel(mts);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnUsluga;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTip;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblKlijent;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblZaposleni;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JLabel txtUkupno;
    // End of variables declaration//GEN-END:variables

}
