/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import domen.Dokument;
import domen.StavkaDokumenta;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logika.Kontroler;
import konstante.Mod;
import modeli.ModelTabeleKlijenti;
import modeli.ModelTabeleStavke;

/**
 *
 * @author stefa
 */
public class FrmKreirajDokument extends javax.swing.JFrame {

    Dokument d;
    ArrayList<StavkaDokumenta> listaStavki = new ArrayList<>();
    StavkaDokumenta sd;
    ModelTabeleKlijenti mtk;

    double ukupnaCena = 0;

    public FrmKreirajDokument() {
        initComponents();
        setLocationRelativeTo(null);
        txtZaposleni.setText(" " + Kontroler.getInstance().getUlogovan());
        txtZaposleni.setForeground(Color.BLUE);
        popuniTabeluKlijenata();
        sd = new StavkaDokumenta();
        d = new Dokument();
        d.setZaposleni(Kontroler.getInstance().getUlogovan());
        tblStavke.setModel(new ModelTabeleStavke(listaStavki));

    }

    public void setSd(StavkaDokumenta sd) {
        this.sd = sd;
    }

    public void dodajStavku(StavkaDokumenta sd) {
        listaStavki.add(sd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtZaposleni = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijent = new javax.swing.JTable();
        txtFilter = new javax.swing.JTextField();
        txtKlijent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtUkupno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPronadji = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnUsluga = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPrikaziSve = new javax.swing.JButton();
        cbTip = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        btnPrikaziDokumente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miKreirajKlijenta = new javax.swing.JMenuItem();
        miUcitajKlijente = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miKreirajUslugu = new javax.swing.JMenuItem();
        miUcitajUsluge = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Ulogovan zaposleni");

        txtZaposleni.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtZaposleni.setText("Zaposleni");

        jLabel2.setText("Pretrazi klijenta po nazivu:");

        tblKlijent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKlijent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKlijentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKlijent);

        txtKlijent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel4.setText("Ukupna cena:");

        btnSacuvaj.setText("Sacuvaj dokument");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        txtUkupno.setText("0");

        jLabel8.setText("Izabrani klijent:");

        btnPronadji.setText("Pronadji");
        btnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiActionPerformed(evt);
            }
        });

        jLabel10.setText("RSD");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnUsluga.setText("Dodaj stavku");
        btnUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUslugaActionPerformed(evt);
            }
        });

        jLabel9.setText("Stavke dokumenta:");

        btnPrikaziSve.setText("Prikazi sve");
        btnPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveActionPerformed(evt);
            }
        });

        cbTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Racun", "Predracun", "Ponuda" }));

        jLabel6.setText("Tip dokumenta:");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U obradi", "Izdat" }));

        jLabel7.setText("Status dokumenta:");

        jLabel11.setText("Datum:");

        txtDatum.setText("01.01.2024");

        btnPrikaziDokumente.setText("Prikazi dokumente");
        btnPrikaziDokumente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDokumenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrikaziSve))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKlijent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(168, 168, 168))
                            .addComponent(jScrollPane1))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(286, 286, 286)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addGap(401, 401, 401)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrikaziDokumente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(btnPronadji)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPrikaziSve))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsluga)
                            .addComponent(btnObrisi))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtUkupno)
                                .addComponent(jLabel10))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(btnSacuvaj)
                .addGap(18, 18, 18)
                .addComponent(btnPrikaziDokumente)
                .addGap(18, 18, 18))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Kreiranje dokumenata");

        jMenu6.setText("Rad sa klijentima");

        miKreirajKlijenta.setText("Kreiraj klijenta");
        miKreirajKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajKlijentaActionPerformed(evt);
            }
        });
        jMenu6.add(miKreirajKlijenta);

        miUcitajKlijente.setText("Pregled klijenata");
        miUcitajKlijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUcitajKlijenteActionPerformed(evt);
            }
        });
        jMenu6.add(miUcitajKlijente);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Rad sa uslugama");

        miKreirajUslugu.setText("Kreiraj uslugu");
        miKreirajUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajUsluguActionPerformed(evt);
            }
        });
        jMenu7.add(miKreirajUslugu);

        miUcitajUsluge.setText("Pregled usluga");
        miUcitajUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUcitajUslugeActionPerformed(evt);
            }
        });
        jMenu7.add(miUcitajUsluge);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtZaposleni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(479, 479, 479))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtZaposleni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void miUcitajKlijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUcitajKlijenteActionPerformed
        FrmNadjiKlijente fnk = new FrmNadjiKlijente(tblKlijent);
        fnk.setVisible(true);
    }//GEN-LAST:event_miUcitajKlijenteActionPerformed

    private void miKreirajUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajUsluguActionPerformed
        FrmUsluga fku = new FrmUsluga(Mod.KREIRAJ);
        fku.setVisible(true);
    }//GEN-LAST:event_miKreirajUsluguActionPerformed

    private void miUcitajUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUcitajUslugeActionPerformed
        FrmNadjiUsluge fnu = new FrmNadjiUsluge();
        fnu.setVisible(true);;
    }//GEN-LAST:event_miUcitajUslugeActionPerformed

    private void miKreirajKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajKlijentaActionPerformed
        FrmKlijent fkk = new FrmKlijent(tblKlijent, Mod.KREIRAJ);
        fkk.setVisible(true);
    }//GEN-LAST:event_miKreirajKlijentaActionPerformed

    private void btnPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveActionPerformed
        popuniTabeluKlijenata();
    }//GEN-LAST:event_btnPrikaziSveActionPerformed

    private void btnUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUslugaActionPerformed
        int red = tblKlijent.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati klijenta!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtKlijent.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Morate izabrati klijenta!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        FrmKreirajStavku fks = new FrmKreirajStavku(this, true);
        fks.setVisible(true);
        ukupnaCena += sd.getCenaStavke();
        txtUkupno.setText(String.valueOf(ukupnaCena));

    }//GEN-LAST:event_btnUslugaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
        int red = tblStavke.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku dokumenta", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            StavkaDokumenta s = mts.vratiStavku(red);
            this.ukupnaCena -= s.getCenaStavke();
            txtUkupno.setText(String.valueOf(ukupnaCena));
            mts.obrisiStavku(s);
            popuniTabeluStavki();
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiActionPerformed
        List<Klijent> listaKlijenata = Kontroler.getInstance().nadjiKlijente(txtFilter.getText());
        mtk = new ModelTabeleKlijenti(listaKlijenata);
        tblKlijent.setModel(mtk);
    }//GEN-LAST:event_btnPronadjiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        int red = tblKlijent.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati klijenta!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtUkupno.getText().isEmpty() || txtUkupno.getText().equals("0") || listaStavki.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate izabrati bar jednu uslugu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDatum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti datum!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        d.setUkupnaCena(ukupnaCena);
        d.setDokumentID(-1);
        d.setListaStavki(listaStavki);
        d.setTipDokumenta(String.valueOf(cbTip.getSelectedItem()));
        d.setStatusDokumenta(String.valueOf(cbStatus.getSelectedItem()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        sdf.setLenient(false);
        try {
            Date datum = sdf.parse(txtDatum.getText());
            d.setDatum(datum);
        } catch (ParseException ex) {
            //Logger.getLogger(FrmKreirajDokument.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Uneli ste datum u pogresnom formatu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Kontroler.getInstance().kreirajDokument(d)) {
            refresuj();
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void tblKlijentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKlijentMouseClicked
        int red = tblKlijent.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati klijenta", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            mtk = (ModelTabeleKlijenti) tblKlijent.getModel();
            Klijent k = mtk.vratiKlijenta(red);
            txtKlijent.setText(k.toString());
            txtKlijent.setForeground(Color.RED);
            d.setKlijent(k);
        }
    }//GEN-LAST:event_tblKlijentMouseClicked

    private void btnPrikaziDokumenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDokumenteActionPerformed
        FrmNadjiDokumente fnd = new FrmNadjiDokumente();
        fnd.setVisible(true);
    }//GEN-LAST:event_btnPrikaziDokumenteActionPerformed

    private void popuniTabeluKlijenata() {
        List<Klijent> listaKlijenata = Kontroler.getInstance().vratiListuKlijenata();
        mtk = new ModelTabeleKlijenti(listaKlijenata);
        tblKlijent.setModel(mtk);
    }

    void popuniTabeluStavki() {
        tblStavke.setModel(new ModelTabeleStavke(listaStavki));
    }

    void refresuj() {
        ukupnaCena = 0;
        txtUkupno.setText("0");
        listaStavki = new ArrayList<>();
        tblStavke.setModel(new ModelTabeleStavke(listaStavki));
        sd = new StavkaDokumenta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPrikaziDokumente;
    private javax.swing.JButton btnPrikaziSve;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnUsluga;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem miKreirajKlijenta;
    private javax.swing.JMenuItem miKreirajUslugu;
    private javax.swing.JMenuItem miUcitajKlijente;
    private javax.swing.JMenuItem miUcitajUsluge;
    private javax.swing.JTable tblKlijent;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JLabel txtKlijent;
    private javax.swing.JLabel txtUkupno;
    private javax.swing.JLabel txtZaposleni;
    // End of variables declaration//GEN-END:variables

}
