/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Dokument;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabeleDokumenti;
import transfer.ServerskiObjekat;

/**
 *
 * @author stefa
 */
public class FrmNadjiDokumente extends javax.swing.JFrame {

    ModelTabeleDokumenti mtd;
    Dokument dokument;
    
    public FrmNadjiDokumente() {
        initComponents();
        setLocationRelativeTo(null);
        popuniTabeluDokumenata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnPronadji = new javax.swing.JButton();
        btnPrikaziSve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDokument = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDokument = new javax.swing.JLabel();
        btnUcitaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Pretrazi dokumente po nazivu klijenta:");

        btnPronadji.setText("Pronadji");
        btnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiActionPerformed(evt);
            }
        });

        btnPrikaziSve.setText("Prikazi sve");
        btnPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveActionPerformed(evt);
            }
        });

        tblDokument.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDokument.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokumentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDokument);

        jLabel8.setText("Izabrani dokument:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Rad sa dokumentima");

        txtDokument.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnUcitaj.setText("Izmeni dokument");
        btnUcitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDokument, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnUcitaj, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziSve)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnPronadji)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziSve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDokument, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUcitaj))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiActionPerformed
        List<Dokument> listaDokumenata;
        ServerskiObjekat so = Kontroler.getInstance().nadjiDokumente(txtFilter.getText());
        if (!so.isUspesno()) {
            listaDokumenata = new ArrayList<>();
        }else{
            listaDokumenata = (List<Dokument>) so.getOdgovor();
        }
        JOptionPane.showMessageDialog(null, so.getPoruka());
        mtd = new ModelTabeleDokumenti(listaDokumenata);
        tblDokument.setModel(mtd);
    }//GEN-LAST:event_btnPronadjiActionPerformed

    private void btnPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveActionPerformed
        popuniTabeluDokumenata();
    }//GEN-LAST:event_btnPrikaziSveActionPerformed

    private void tblDokumentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokumentMouseClicked
        int red = tblDokument.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati dokument", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            mtd = (ModelTabeleDokumenti) tblDokument.getModel();
            dokument = mtd.vratiDokument(red);
            txtDokument.setText(dokument.getKlijent().getNazivKlijenta());
            txtDokument.setForeground(Color.RED);
        }
    }//GEN-LAST:event_tblDokumentMouseClicked

    private void btnUcitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajActionPerformed
        int red = tblDokument.getSelectedRow();
        if (red != -1) {
            JOptionPane.showMessageDialog(this, "Dokument je uspesno ucitan!");
            FrmIzmeniDokument fid = new FrmIzmeniDokument(dokument);
            fid.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita dokument", "Greksa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUcitajActionPerformed

    private void popuniTabeluDokumenata() {
        List<Dokument> listaDokumenata;
        ServerskiObjekat so = Kontroler.getInstance().nadjiDokumente("");
        if (!so.isUspesno()) {
            listaDokumenata = new ArrayList<>();
        }else{
            listaDokumenata = (List<Dokument>) so.getOdgovor();
        }
        mtd = new ModelTabeleDokumenti(listaDokumenata);
        tblDokument.setModel(mtd);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaziSve;
    private javax.swing.JButton btnPronadji;
    private javax.swing.JButton btnUcitaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDokument;
    private javax.swing.JLabel txtDokument;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
